# Form implementation generated from reading ui file 'check_ticket.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
)
import cv2
from pyzbar import pyzbar
from PyQt6 import QtWidgets, QtCore
from PyQt6.QtCore import QTimer
from PyQt6.QtGui import QImage, QPixmap
from src.model.checkin_ticket import InfoCheckin
from src.model.staff_current import StaffCurrent
from src.controller.ticket_controller import TicketController
from src.util import toast


class Ui_MainWindow(object):
    def __init__(self, staffCurrent: StaffCurrent):
        self.ticketController = TicketController()
        self.idTicket = None
        self.staffCurrent = staffCurrent

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 510)
        MainWindow.setStyleSheet("font-size: 15px")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.checkin.setGeometry(QtCore.QRect(530, 370, 121, 28))
        self.checkin.setStyleSheet(
            "background: #20c997; border: 2px dashed #adb5bd; border-radius: 10px"
        )
        self.checkin.setObjectName("checkin")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 90, 55, 16))
        self.label.setObjectName("label")
        self.ticket = QtWidgets.QLabel(parent=self.centralwidget)
        self.ticket.setGeometry(QtCore.QRect(590, 90, 181, 16))
        self.ticket.setText("")
        self.ticket.setObjectName("ticket")
        self.chairs = QtWidgets.QLabel(parent=self.centralwidget)
        self.chairs.setGeometry(QtCore.QRect(620, 240, 181, 41))
        self.chairs.setText("")
        self.chairs.setObjectName("chairs")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 250, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 170, 81, 20))
        self.label_5.setObjectName("label_5")
        self.room = QtWidgets.QLabel(parent=self.centralwidget)
        self.room.setGeometry(QtCore.QRect(620, 170, 151, 21))
        self.room.setText("")
        self.room.setObjectName("room")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 290, 81, 20))
        self.label_7.setObjectName("label_7")
        self.popcorn = QtWidgets.QLabel(parent=self.centralwidget)
        self.popcorn.setGeometry(QtCore.QRect(620, 290, 151, 21))
        self.popcorn.setText("")
        self.popcorn.setObjectName("popcorn")
        self.water = QtWidgets.QLabel(parent=self.centralwidget)
        self.water.setGeometry(QtCore.QRect(620, 330, 151, 21))
        self.water.setText("")
        self.water.setObjectName("water")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(530, 330, 81, 20))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(530, 210, 81, 21))
        self.label_13.setObjectName("label_13")
        self.person = QtWidgets.QLabel(parent=self.centralwidget)
        self.person.setGeometry(QtCore.QRect(620, 210, 151, 21))
        self.person.setText("")
        self.person.setObjectName("person")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(530, 130, 81, 20))
        self.label_15.setObjectName("label_15")
        self.calendar = QtWidgets.QLabel(parent=self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(620, 130, 151, 16))
        self.calendar.setText("")
        self.calendar.setObjectName("calendar")
        self.skip = QtWidgets.QPushButton(parent=self.centralwidget)
        self.skip.setGeometry(QtCore.QRect(680, 370, 121, 28))
        self.skip.setStyleSheet(
            "background: #3dd5f3; border: 2px dashed #adb5bd; border-radius: 10px"
        )
        self.skip.setObjectName("skip")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 500, 400))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.image = QtWidgets.QLabel(parent=self.groupBox)
        self.image.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.image.setText("")
        self.image.setObjectName("image")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkin.setText(_translate("MainWindow", "Vào xem"))
        self.label.setText(_translate("MainWindow", "Mã vé :"))
        self.label_4.setText(_translate("MainWindow", "Vị trí ngồi :"))
        self.label_5.setText(_translate("MainWindow", "Phòng :"))
        self.label_7.setText(_translate("MainWindow", "Bỏng ngô :"))
        self.label_10.setText(_translate("MainWindow", "Nước ngọt :"))
        self.label_13.setText(_translate("MainWindow", "Số người :"))
        self.label_15.setText(_translate("MainWindow", "Giờ chiếu :"))
        self.skip.setText(_translate("MainWindow", "Bỏ qua"))
        self.setEvents()
        self.setUp()

    def setUp(self):
        self.cap = cv2.VideoCapture(2)
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_image)
        self.startCamera()

    def setEvents(self):
        self.checkin.clicked.connect(self.clickCheckin)
        self.skip.clicked.connect(self.clickSkip)

    def clickCheckin(self):
        if self.idTicket is None:
            return
        result = self.ticketController.checkinTicket(
            self.idTicket, self.staffCurrent.id
        )
        if result.success is False:
            return toast.toastWarning(result.message)
        self.clear()
        self.startCamera()
        return

    def clickSkip(self):
        self.clear()
        self.startCamera()
        return

    def update_image(self):
        ret, frame = self.cap.read()
        if not ret:
            return
        frame = cv2.resize(frame, (500, 400))
        frame = cv2.flip(frame, 1)
        frame = self.decode_qr(frame)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        h, w, ch = frame.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QImage(
            frame.data, w, h, bytes_per_line, QImage.Format.Format_RGB888
        )
        self.image.setPixmap(QPixmap.fromImage(convert_to_Qt_format))

    def decode_qr(self, frame):
        decoded_objects = pyzbar.decode(frame)
        for obj in decoded_objects:
            self.stopCamera()
            ticket = obj.data.decode("utf-8")
            self.idTicket = ticket
            self.handleProcessInfo()
        return frame

    def stopCamera(self):
        self.timer.stop()

    def startCamera(self):
        self.timer.start()

    def clear(self):
        self.ticket.setText("")
        self.calendar.setText("")
        self.room.setText("")
        self.person.setText("")
        self.chairs.setText("")
        self.popcorn.setText("")
        self.water.setText("")
        self.idTicket = None

    def handleProcessInfo(self):
        if self.idTicket is None:
            return
        result = self.ticketController.getInfoTicket(self.idTicket)
        if result.success is False:
            return toast.toastWarning(result.message)
        info = result.data
        self.pushInfo(info)
        return

    def pushInfo(self, info: InfoCheckin):
        self.ticket.setText(info.ticket)
        self.calendar.setText(info.calendar)
        self.room.setText(f"P{info.room}")
        self.person.setText(str(info.person))
        self.chairs.setText(info.chairs)
        self.popcorn.setText(str(info.popcorn))
        self.water.setText(str(info.water))
        return


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
