# Form implementation generated from reading ui file 'frame_payment.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets
from src.util import number


class Ui_Payment(object):
    def __init__(self, formInfo) -> None:
        self.formInfo = formInfo
        self.total_number = 0
        self.change_number = 0

    def setupUi(self, Payment):
        Payment.setObjectName("Payment")
        Payment.setWindowIcon(
            QtGui.QIcon(
                os.path.join(
                    os.path.abspath(
                        os.path.join(os.path.dirname(__file__), "..", "..", "..")
                    ),
                    "public/logo.png",
                )
            )
        )
        Payment.resize(691, 400)
        self.centralwidget = QtWidgets.QWidget(parent=Payment)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-10, -10, 711, 431))
        self.groupBox.setStyleSheet("font-size: 15px; ")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 511, 41))
        self.label_2.setStyleSheet("font-size: 30px; font-weight: bold; color: #20c997")
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 141, 311))
        self.groupBox_2.setStyleSheet(
            " QLabel{font-size: 15px; } QGroupBox{border: 1px solid black; border-right: none}"
        )
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(90, 70, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(80, 190, 61, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(70, 230, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(90, 270, 51, 31))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(60, 110, 71, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(70, 150, 71, 31))
        self.label_12.setObjectName("label_12")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 80, 221, 311))
        self.groupBox_3.setStyleSheet(
            "QTextEdit, QLabel{font-size: 18px; } QGroupBox{border: 1px solid black; border-left: none}"
        )
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.name_customer = QtWidgets.QLabel(parent=self.groupBox_3)
        self.name_customer.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.name_customer.setText("")
        self.name_customer.setObjectName("name_customer")
        self.email = QtWidgets.QLabel(parent=self.groupBox_3)
        self.email.setGeometry(QtCore.QRect(10, 70, 191, 31))
        self.email.setText("")
        self.email.setObjectName("email")
        self.chairs = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.chairs.setGeometry(QtCore.QRect(10, 190, 201, 31))
        self.chairs.setStyleSheet("border: none; background: transparent;")
        self.chairs.setReadOnly(True)
        self.chairs.setObjectName("chairs")
        self.popcorn = QtWidgets.QLabel(parent=self.groupBox_3)
        self.popcorn.setGeometry(QtCore.QRect(10, 230, 81, 31))
        self.popcorn.setText("")
        self.popcorn.setObjectName("popcorn")
        self.water = QtWidgets.QLabel(parent=self.groupBox_3)
        self.water.setGeometry(QtCore.QRect(10, 270, 81, 31))
        self.water.setText("")
        self.water.setObjectName("water")
        self.name_movie = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.name_movie.setGeometry(QtCore.QRect(10, 110, 201, 31))
        self.name_movie.setStyleSheet("border: none; background: transparent;")
        self.name_movie.setReadOnly(True)
        self.name_movie.setObjectName("name_movie")
        self.calendar = QtWidgets.QLabel(parent=self.groupBox_3)
        self.calendar.setGeometry(QtCore.QRect(10, 150, 191, 31))
        self.calendar.setText("")
        self.calendar.setObjectName("calendar")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(380, 80, 121, 311))
        self.groupBox_4.setStyleSheet(
            "QLabel{font-size: 18px} QGroupBox{border: 1px solid black}"
        )
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.total_popcorn = QtWidgets.QLabel(parent=self.groupBox_4)
        self.total_popcorn.setGeometry(QtCore.QRect(10, 230, 81, 31))
        self.total_popcorn.setText("")
        self.total_popcorn.setObjectName("total_popcorn")
        self.total_water = QtWidgets.QLabel(parent=self.groupBox_4)
        self.total_water.setGeometry(QtCore.QRect(10, 270, 81, 31))
        self.total_water.setText("")
        self.total_water.setObjectName("total_water")
        self.total_ticket = QtWidgets.QLabel(parent=self.groupBox_4)
        self.total_ticket.setGeometry(QtCore.QRect(10, 190, 81, 31))
        self.total_ticket.setText("")
        self.total_ticket.setObjectName("total_ticket")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(530, 170, 51, 31))
        self.label_20.setObjectName("label_20")
        self.total = QtWidgets.QLabel(parent=self.groupBox)
        self.total.setGeometry(QtCore.QRect(590, 170, 101, 31))
        self.total.setStyleSheet("color: red; font-size: 18px")
        self.total.setObjectName("total")
        self.btn_done = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_done.setGeometry(QtCore.QRect(540, 210, 141, 28))
        self.btn_done.setStyleSheet(
            "QPushButton{border-radius: 10px; background: #FFB578} QPushButton:hover{color: white}"
        )
        self.btn_done.setObjectName("btn_done")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(150, 70, 101, 41))
        self.label_4.setStyleSheet("font-size: 18px; font-weight: bold")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(400, 70, 71, 41))
        self.label_5.setStyleSheet("font-size: 18px; font-weight: bold")
        self.label_5.setObjectName("label_5")
        Payment.setCentralWidget(self.centralwidget)

        self.retranslateUi(Payment)
        QtCore.QMetaObject.connectSlotsByName(Payment)

    def retranslateUi(self, Payment):
        _translate = QtCore.QCoreApplication.translate
        Payment.setWindowTitle(_translate("Payment", "Payment"))
        self.label_2.setText(_translate("Payment", "Xác nhận thông tin và thanh toán"))
        self.label.setText(_translate("Payment", "Tên khách hàng:"))
        self.label_3.setText(_translate("Payment", " Email:"))
        self.label_6.setText(_translate("Payment", "Mã ghế:"))
        self.label_7.setText(_translate("Payment", "Bắp rang:"))
        self.label_8.setText(_translate("Payment", " Nước:"))
        self.label_11.setText(_translate("Payment", " Tên phim:"))
        self.label_12.setText(_translate("Payment", "Thời gian:"))
        self.chairs.setHtml(
            _translate(
                "Payment",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18px; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.name_movie.setHtml(
            _translate(
                "Payment",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18px; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.label_20.setText(_translate("Payment", " Tổng:"))
        self.btn_done.setText(_translate("Payment", "Kết thúc"))
        self.label_4.setText(_translate("Payment", "Thông tin"))
        self.label_5.setText(_translate("Payment", "Đơn giá"))
        self.setData()
        self.setEvents()

    def setData(self):
        self.name_customer.setText(self.formInfo.nameCustomer.text())
        self.email.setText(self.formInfo.email.text())
        self.name_movie.setText(self.formInfo.nameMovie.currentText())
        self.calendar.setText(self.formInfo.calender.currentText())
        self.chairs.setPlainText(self.formInfo.listChair.toPlainText())
        self.popcorn.setText(str(self.formInfo.num_popcorn.value()))
        self.water.setText(str(self.formInfo.num_water.value()))
        self.total_ticket.setText(str(self.formInfo.total_ticket.text()))
        self.total_popcorn.setText(str(self.formInfo.total_popcorn.text()))
        self.total_water.setText(str(self.formInfo.total_water.text()))
        self.total_number = (
            self.formInfo.totalWater
            + self.formInfo.totalPopcorn
            + self.formInfo.totalTicket
        )
        self.total.setText(
            f"{number.convertPrice(self.formInfo.totalWater + self.formInfo.totalPopcorn + self.formInfo.totalTicket)} đ"
        )

    def setEvents(self):
        self.btn_done.clicked.connect(self.clickDone)

    def clickDone(self):
        self.formInfo.order()
