# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
)

from PyQt6 import QtCore, QtGui, QtWidgets
from src.model.staff_current import StaffCurrent
from src.view.staff.account_staff import Ui_accountStaff
from src.view.staff.staff_working import Ui_StafWorking


class Ui_Buy_Ticket(object):
    def __init__(self):
        self.staffCurrent = None

    def setupUi(self, Buy_Ticket):
        Buy_Ticket.setObjectName("Buy_Ticket")
        Buy_Ticket.resize(1108, 701)
        self.centralwidget = QtWidgets.QWidget(parent=Buy_Ticket)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 201, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutLogin = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutLogin.setContentsMargins(0, 0, 0, 0)
        self.layoutLogin.setObjectName("layoutLogin")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 0, 891, 701))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layoutWorking = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layoutWorking.setContentsMargins(0, 0, 0, 0)
        self.layoutWorking.setObjectName("layoutWorking")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(200, 0, 20, 701))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        Buy_Ticket.setCentralWidget(self.centralwidget)

        self.retranslateUi(Buy_Ticket)
        QtCore.QMetaObject.connectSlotsByName(Buy_Ticket)

    def retranslateUi(self, Buy_Ticket):
        _translate = QtCore.QCoreApplication.translate
        Buy_Ticket.setWindowTitle(_translate("Buy_Ticket", "Buy Ticket"))
        self.showFrameAccountStaff()
        self.showRequireLogin()
        self.staffCurrent = StaffCurrent(123, "cacs", "staff")

    def showRequireLogin(self):
        btnRequireLogin = QtWidgets.QPushButton()
        btnRequireLogin.setStyleSheet("font-size: 25px;  background: transparent;")
        btnRequireLogin.setObjectName("btnRequireLogin")
        btnRequireLogin.setText("Đăng nhập để sử dụng")
        self.clearLayoutWorking()
        self.layoutWorking.addWidget(btnRequireLogin)

    def showFrameAccountStaff(self):
        self.clearLayoutLogin()
        child_widget = QtWidgets.QWidget()
        child_ui = Ui_accountStaff(self)
        child_ui.setupUi(child_widget)
        self.layoutLogin.addWidget(child_widget)

    def showFrameWorking(self):
        self.clearLayoutWorking()
        child_widget = QtWidgets.QWidget()
        child_ui = Ui_StafWorking(self.staffCurrent)
        child_ui.setupUi(child_widget)
        self.layoutWorking.addWidget(child_widget)

    def clearLayoutLogin(self):
        while self.layoutLogin.count():
            item = self.layoutLogin.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()

    def clearLayoutWorking(self):
        while self.layoutWorking.count():
            item = self.layoutWorking.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()

    def setStaffCurrent(self, staffCurrent: StaffCurrent):
        self.staffCurrent = staffCurrent


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Buy_Ticket = QtWidgets.QMainWindow()
    ui = Ui_Buy_Ticket()
    ui.setupUi(Buy_Ticket)
    Buy_Ticket.show()
    sys.exit(app.exec())
