# Form implementation generated from reading ui file 'staff_working.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StafWorking(object):
    def setupUi(self, StafWorking):
        StafWorking.setObjectName("StafWorking")
        StafWorking.resize(891, 701)
        self.centralwidget = QtWidgets.QWidget(parent=StafWorking)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.form = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.form.setContentsMargins(0, 0, 0, 0)
        self.form.setObjectName("form")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(390, 0, 501, 701))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.chair_location = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.chair_location.setContentsMargins(0, 0, 0, 0)
        self.chair_location.setObjectName("chair_location")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 30, 20, 651))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        StafWorking.setCentralWidget(self.centralwidget)

        self.retranslateUi(StafWorking)
        QtCore.QMetaObject.connectSlotsByName(StafWorking)

    def retranslateUi(self, StafWorking):
        _translate = QtCore.QCoreApplication.translate
        StafWorking.setWindowTitle(_translate("StafWorking", "Staff Working"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StafWorking = QtWidgets.QMainWindow()
    ui = Ui_StafWorking()
    ui.setupUi(StafWorking)
    StafWorking.show()
    sys.exit(app.exec())
