# Form implementation generated from reading ui file 'TKphim.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TKphim(object):
    def setupUi(self, TKphim):
        TKphim.setObjectName("TKphim")
        TKphim.resize(1000, 660)
        self.centralwidget = QtWidgets.QWidget(parent=TKphim)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(380, -20, 20, 721))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 0, 191, 61))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color:rgb(92, 95, 255);")
        self.label.setObjectName("label")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(420, 200, 501, 351))
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(430, 30, 131, 111))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 111, 101))
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../../../ảnh python/film-reel.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.groupBox_theothoigian = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_theothoigian.setGeometry(QtCore.QRect(40, 200, 321, 351))
        self.groupBox_theothoigian.setStyleSheet("\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
" border-radius: 25px;\n"
"  border: 2px solid #73AD21;")
        self.groupBox_theothoigian.setObjectName("groupBox_theothoigian")
        self.button_ngay = QtWidgets.QRadioButton(parent=self.groupBox_theothoigian)
        self.button_ngay.setGeometry(QtCore.QRect(30, 40, 121, 31))
        self.button_ngay.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border: white;")
        self.button_ngay.setObjectName("button_ngay")
        self.button_thang = QtWidgets.QRadioButton(parent=self.groupBox_theothoigian)
        self.button_thang.setGeometry(QtCore.QRect(30, 120, 121, 41))
        self.button_thang.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border: white;")
        self.button_thang.setObjectName("button_thang")
        self.button_nam = QtWidgets.QRadioButton(parent=self.groupBox_theothoigian)
        self.button_nam.setGeometry(QtCore.QRect(30, 220, 101, 31))
        self.button_nam.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border: white;")
        self.button_nam.setObjectName("button_nam")
        self.box_ngay = QtWidgets.QSpinBox(parent=self.groupBox_theothoigian)
        self.box_ngay.setGeometry(QtCore.QRect(50, 80, 101, 31))
        self.box_ngay.setMinimumSize(QtCore.QSize(101, 31))
        self.box_ngay.setMaximumSize(QtCore.QSize(101, 31))
        self.box_ngay.setStyleSheet("border:707070;")
        self.box_ngay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_ngay.setMinimum(1)
        self.box_ngay.setMaximum(31)
        self.box_ngay.setObjectName("box_ngay")
        self.box_thang = QtWidgets.QSpinBox(parent=self.groupBox_theothoigian)
        self.box_thang.setGeometry(QtCore.QRect(50, 170, 101, 31))
        self.box_thang.setMinimumSize(QtCore.QSize(101, 31))
        self.box_thang.setMaximumSize(QtCore.QSize(101, 31))
        self.box_thang.setStyleSheet("border:707070;")
        self.box_thang.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_thang.setMinimum(1)
        self.box_thang.setMaximum(12)
        self.box_thang.setObjectName("box_thang")
        self.box_nam = QtWidgets.QSpinBox(parent=self.groupBox_theothoigian)
        self.box_nam.setGeometry(QtCore.QRect(50, 260, 101, 31))
        self.box_nam.setMinimumSize(QtCore.QSize(101, 31))
        self.box_nam.setMaximumSize(QtCore.QSize(101, 31))
        self.box_nam.setStyleSheet("border:707070;")
        self.box_nam.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_nam.setMinimum(2018)
        self.box_nam.setMaximum(2024)
        self.box_nam.setObjectName("box_nam")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 70, 291, 91))
        self.groupBox_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
" border-radius: 25px;\n"
"  border: 2px solid #73AD21;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.txt_tenphim = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.txt_tenphim.setGeometry(QtCore.QRect(30, 30, 231, 31))
        self.txt_tenphim.setObjectName("txt_tenphim")
     

        self.retranslateUi(TKphim)
        QtCore.QMetaObject.connectSlotsByName(TKphim)

    def retranslateUi(self, TKphim):
        _translate = QtCore.QCoreApplication.translate
        TKphim.setWindowTitle(_translate("TKphim", "MainWindow"))
        self.label.setText(_translate("TKphim", "Bộ lọc thống kê"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("TKphim", "Tên phim"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("TKphim", "Số lượng vé"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("TKphim", "Doanh thu"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("TKphim", "Xuất file"))
        self.groupBox_theothoigian.setTitle(_translate("TKphim", "Theo thời gian"))
        self.button_ngay.setText(_translate("TKphim", "Theo ngày"))
        self.button_thang.setText(_translate("TKphim", "Theo tháng"))
        self.button_nam.setText(_translate("TKphim", "Theo năm"))
        self.groupBox_2.setTitle(_translate("TKphim", "Theo tên phim"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TKphim = QtWidgets.QMainWindow()
    ui = Ui_TKphim()
    ui.setupUi(TKphim)
    TKphim.show()
    sys.exit(app.exec())
