# Form implementation generated from reading ui file 'add_lichchieu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
)

from PyQt6 import QtCore, QtGui, QtWidgets
from datetime import datetime

from src.controller.LichChieu_controller import LichChieuController


class Ui_add_lichchieu(object):

    def __init__(self):
        self.sex = None
        self.lichChieuController = LichChieuController()


    def setupUi(self, add_lichchieu):
        add_lichchieu.setObjectName("add_lichchieu")
        add_lichchieu.resize(966, 670)
        self.centralwidget = QtWidgets.QWidget(parent=add_lichchieu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 201, 71))
        self.label.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"text-decoration: underline;color:rgb(85, 170, 255)")
        self.label.setObjectName("label")
        self.t = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.t.setGeometry(QtCore.QRect(30, 110, 401, 271))
        self.t.setMaximumSize(QtCore.QSize(401, 16777215))
        self.t.setStyleSheet("font: 75 13pt \"Times New Roman\";")
        self.t.setObjectName("t")
        self.t.setColumnCount(3)
        self.t.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t.setHorizontalHeaderItem(2, item)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 40, 121, 51))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"text-decoration: underline;color:rgb(85, 170, 255)")
        self.label_2.setObjectName("label_2")
        self.date_lichchieu = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_lichchieu.setGeometry(QtCore.QRect(670, 50, 91, 31))
        self.date_lichchieu.setObjectName("date_lichchieu")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(500, 110, 391, 271))
        self.graphicsView.setObjectName("graphicsView")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 170, 71, 31))
        self.label_3.setStyleSheet("font: 13pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 210, 91, 21))
        self.label_4.setStyleSheet("font: 13pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.buttonThem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonThem.setGeometry(QtCore.QRect(630, 130, 75, 23))
        self.buttonThem.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.buttonThem.setAutoFillBackground(False)
        self.buttonThem.setStyleSheet("font: 75 11pt \"Times New Roman\";")
        self.buttonThem.setObjectName("buttonThem")
        self.button_Lammoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_Lammoi.setGeometry(QtCore.QRect(750, 130, 75, 23))
        self.button_Lammoi.setStyleSheet("font: 75 11pt \"Times New Roman\";")
        self.button_Lammoi.setObjectName("button_Lammoi")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 260, 91, 21))
        self.label_5.setStyleSheet("font: 13pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.timeAdd = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timeAdd.setGeometry(QtCore.QRect(630, 170, 111, 22))
        self.timeAdd.setObjectName("timeAdd")
        self.line_IPphim = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_IPphim.setGeometry(QtCore.QRect(630, 249, 171, 31))
        self.line_IPphim.setStyleSheet("font: 13pt \"Times New Roman\";")
        self.line_IPphim.setObjectName("line_IPphim")
        self.cboLichchieu = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cboLichchieu.setGeometry(QtCore.QRect(630, 210, 111, 22))
        self.cboLichchieu.setObjectName("cboLichchieu")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.cboLichchieu.addItem("")
        self.buttonCheck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonCheck.setGeometry(QtCore.QRect(690, 340, 81, 31))
        self.buttonCheck.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.buttonCheck.setObjectName("buttonCheck")
        self.text_IPphim = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.text_IPphim.setGeometry(QtCore.QRect(630, 290, 171, 31))
        self.text_IPphim.setReadOnly(True)
        self.text_IPphim.setPlainText("")
        self.text_IPphim.setObjectName("text_IPphim")
        self.buttonOk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonOk.setGeometry(QtCore.QRect(800, 50, 81, 31))
        self.buttonOk.setObjectName("buttonOk")
       
        self.retranslateUi(add_lichchieu)
        QtCore.QMetaObject.connectSlotsByName(add_lichchieu)

        self.setEvents()

    def retranslateUi(self, add_lichchieu):
        _translate = QtCore.QCoreApplication.translate
        add_lichchieu.setWindowTitle(_translate("add_lichchieu", "add_lichchieu"))
        self.label.setText(_translate("add_lichchieu", "Lịch chiếu hiện tại"))
        item = self.t.horizontalHeaderItem(0)
        item.setText(_translate("add_lichchieu", "Thời gian"))
        item = self.t.horizontalHeaderItem(1)
        item.setText(_translate("add_lichchieu", "Phòng chiếu"))
        item = self.t.horizontalHeaderItem(2)
        item.setText(_translate("add_lichchieu", "Tên phim"))
        self.label_2.setText(_translate("add_lichchieu", "Lựa chọn lịch "))
        self.label_3.setText(_translate("add_lichchieu", "Thời gian"))
        self.label_4.setText(_translate("add_lichchieu", "Phòng chiếu"))
        self.buttonThem.setText(_translate("add_lichchieu", "Thêm"))
        self.button_Lammoi.setText(_translate("add_lichchieu", "Làm mới"))
        self.label_5.setText(_translate("add_lichchieu", "Id phim"))
        self.cboLichchieu.setItemText(0, _translate("add_lichchieu", "P1"))
        self.cboLichchieu.setItemText(1, _translate("add_lichchieu", "P2"))
        self.cboLichchieu.setItemText(2, _translate("add_lichchieu", "P3"))
        self.cboLichchieu.setItemText(3, _translate("add_lichchieu", "P4"))
        self.cboLichchieu.setItemText(4, _translate("add_lichchieu", "P5"))
        self.cboLichchieu.setItemText(5, _translate("add_lichchieu", "P6"))
        self.cboLichchieu.setItemText(6, _translate("add_lichchieu", "P7"))
        self.cboLichchieu.setItemText(7, _translate("add_lichchieu", "P8"))
        self.cboLichchieu.setItemText(8, _translate("add_lichchieu", "P9"))
        self.cboLichchieu.setItemText(9, _translate("add_lichchieu", "P10"))
        self.buttonCheck.setText(_translate("add_lichchieu", "Kiểm tra id"))
        self.buttonOk.setText(_translate("add_lichchieu", "OK"))

        

    def setEvents(self):
        self.buttonOk.mousePressEvent = self.clickButtonOk
      

    def getDate(self):
        date = self.date_lichchieu.text()
        # date_str = date.toString("dd-MM-yyyy")
        return date
        
    def clickButtonOk(self, event):
        date = self.getDate()
        dateBegin = datetime.strptime(date, "%d/%m/%Y")
        timesBegin = dateBegin.timestamp()
        timesEnd = dateBegin + 86400 - 1
       
        

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_lichchieu = QtWidgets.QMainWindow()
    ui = Ui_add_lichchieu()
    ui.setupUi(add_lichchieu)
    add_lichchieu.show()
    sys.exit(app.exec())
