# Form implementation generated from reading ui file 'info_lichchieu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_infor_lichchieu(object):
    def setupUi(self, infor_lichchieu):
        infor_lichchieu.setObjectName("infor_lichchieu")
        infor_lichchieu.resize(1000, 670)
        self.centralwidget = QtWidgets.QWidget(parent=infor_lichchieu)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 40, 20, 621))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 231, 41))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.date_timkiem = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_timkiem.setGeometry(QtCore.QRect(40, 90, 121, 31))
        self.date_timkiem.setObjectName("date_timkiem")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(700, 80, 201, 41))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(486, 230, 61, 20))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 300, 91, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 360, 81, 20))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 420, 81, 20))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 480, 81, 20))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.button_sua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_sua.setGeometry(QtCore.QRect(520, 550, 81, 41))
        self.button_sua.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"border: 3px solid #2980b9 ; /* Đường viền đen dày 2px */\n"
"border-radius: 15px;\n"
" color: #ffffff;\n"
" background-color: #3498db")
        self.button_sua.setObjectName("button_sua")
        self.button_xoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_xoa.setGeometry(QtCore.QRect(730, 550, 75, 41))
        self.button_xoa.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"border: 1px solid white ; /* Đường viền đen dày 2px */\n"
"border-radius: 15px;\n"
"background-color: #e74c3c;\n"
" color: #ffffff;")
        self.button_xoa.setObjectName("button_xoa")
        self.txt_tenphim = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_tenphim.setGeometry(QtCore.QRect(580, 220, 221, 31))
        self.txt_tenphim.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"border: 3px solid white ; /* Đường viền đen dày 2px */\n"
"border-radius: 15px;")
        self.txt_tenphim.setObjectName("txt_tenphim")
        self.txt_phongchieu = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_phongchieu.setGeometry(QtCore.QRect(580, 290, 221, 31))
        self.txt_phongchieu.setStyleSheet("border: 3px solid white ; /* Đường viền đen dày 2px */\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;")
        self.txt_phongchieu.setObjectName("txt_phongchieu")
        self.date_ngaychieu = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_ngaychieu.setGeometry(QtCore.QRect(580, 350, 111, 31))
        self.date_ngaychieu.setObjectName("date_ngaychieu")
        self.time_begin = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_begin.setGeometry(QtCore.QRect(580, 420, 111, 31))
        self.time_begin.setObjectName("time_begin")
        self.time_end = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_end.setGeometry(QtCore.QRect(580, 470, 111, 31))
        self.time_end.setObjectName("time_end")
        self.table_lichchieu = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_lichchieu.setGeometry(QtCore.QRect(30, 230, 321, 191))
        self.table_lichchieu.setObjectName("table_lichchieu")
        self.table_lichchieu.setColumnCount(5)
        self.table_lichchieu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(4, item)
        self.button_themlichchieu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_themlichchieu.setGeometry(QtCore.QRect(30, 460, 321, 41))
        self.button_themlichchieu.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border: 5px solid white ; /* Đường viền đen dày 2px */\n"
"border-radius: 15px;\n"
"background-color:#e67e22;\n"
" color: #ffffff;")
        self.button_themlichchieu.setObjectName("button_themlichchieu")
        self.button_timkiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_timkiem.setGeometry(QtCore.QRect(250, 120, 81, 41))
        self.button_timkiem.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"border: 3px solid white ; /* Đường viền đen dày 2px */\n"
"border-radius: 15px;\n"
"background-color:#27ae60;\n"
" color: #ffffff;")
        self.button_timkiem.setObjectName("button_timkiem")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 150, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(460, 30, 211, 171))
        self.widget.setObjectName("widget")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 191, 151))
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setPixmap(QtGui.QPixmap("../../../../../ảnh python/video-camera.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(690, 120, 231, 51))
        self.label_10.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 92, 43);")
        self.label_10.setObjectName("label_10")
        infor_lichchieu.setCentralWidget(self.centralwidget)

        self.retranslateUi(infor_lichchieu)
        QtCore.QMetaObject.connectSlotsByName(infor_lichchieu)

    def retranslateUi(self, infor_lichchieu):
        _translate = QtCore.QCoreApplication.translate
        infor_lichchieu.setWindowTitle(_translate("infor_lichchieu", "MainWindow"))
        self.label.setText(_translate("infor_lichchieu", "DANH SÁCH LỊCH CHIẾU"))
        self.label_2.setText(_translate("infor_lichchieu", "SỬA LỊCH CHIẾU"))
        self.label_3.setText(_translate("infor_lichchieu", "Tên phim"))
        self.label_4.setText(_translate("infor_lichchieu", "Phòng chiếu"))
        self.label_5.setText(_translate("infor_lichchieu", "Ngày chiếu"))
        self.label_6.setText(_translate("infor_lichchieu", "Giờ bắt đầu"))
        self.label_7.setText(_translate("infor_lichchieu", "Giờ kết thúc"))
        self.button_sua.setText(_translate("infor_lichchieu", "Sửa"))
        self.button_xoa.setText(_translate("infor_lichchieu", "Xoá"))
        self.txt_tenphim.setHtml(_translate("infor_lichchieu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        item = self.table_lichchieu.horizontalHeaderItem(0)
        item.setText(_translate("infor_lichchieu", "Tên phim"))
        item = self.table_lichchieu.horizontalHeaderItem(1)
        item.setText(_translate("infor_lichchieu", "Phòng chiếu"))
        item = self.table_lichchieu.horizontalHeaderItem(2)
        item.setText(_translate("infor_lichchieu", "Ngày chiếu"))
        item = self.table_lichchieu.horizontalHeaderItem(3)
        item.setText(_translate("infor_lichchieu", "Giờ bắt đầu"))
        item = self.table_lichchieu.horizontalHeaderItem(4)
        item.setText(_translate("infor_lichchieu", "Giờ kết thúc"))
        self.button_themlichchieu.setText(_translate("infor_lichchieu", "+ THÊM LỊCH CHIẾU "))
        self.button_timkiem.setText(_translate("infor_lichchieu", "Tìm kiếm"))
        self.comboBox.setItemText(0, _translate("infor_lichchieu", "Phòng 1"))
        self.comboBox.setItemText(1, _translate("infor_lichchieu", "Phòng 2"))
        self.comboBox.setItemText(2, _translate("infor_lichchieu", "Phòng 3"))
        self.comboBox.setItemText(3, _translate("infor_lichchieu", "Phòng 4"))
        self.label_10.setText(_translate("infor_lichchieu", "Vui lòng nhập đầy đủ thông tin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infor_lichchieu = QtWidgets.QMainWindow()
    ui = Ui_infor_lichchieu()
    ui.setupUi(infor_lichchieu)
    infor_lichchieu.show()
    sys.exit(app.exec())
