# Form implementation generated from reading ui file 'them_lichchieu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
)

from PyQt6 import QtCore, QtGui, QtWidgets
from src.controller.LichChieu_controller import LichChieuController
from src.util import toast


class Ui_them_lichchieu(object):
    def __init__(self):
        self.lichChieuController = LichChieuController()
        self.listMovie = []

    def setupUi(self, them_lichchieu):
        them_lichchieu.setObjectName("them_lichchieu")
        them_lichchieu.resize(1000, 1301)
        self.centralwidget = QtWidgets.QWidget(parent=them_lichchieu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 231, 41))
        self.label.setStyleSheet('font: 14pt "MS Shell Dlg 2";')
        self.label.setObjectName("label")
        self.date_timkiem = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_timkiem.setGeometry(QtCore.QRect(50, 80, 121, 31))
        self.date_timkiem.setObjectName("date_timkiem")
        self.button_sua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_sua.setGeometry(QtCore.QRect(530, 540, 81, 41))
        self.button_sua.setStyleSheet(
            'font: 10pt "MS Shell Dlg 2";\n'
            "border: 3px solid #2980b9 ; /* Đường viền đen dày 2px */\n"
            "border-radius: 15px;\n"
            " color: #ffffff;\n"
            " background-color: #3498db"
        )
        self.button_sua.setObjectName("button_sua")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 290, 91, 20))
        self.label_4.setStyleSheet('font: 10pt "MS Shell Dlg 2";')
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(700, 110, 231, 51))
        self.label_10.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n'
            "text-decoration: underline;\n"
            "color: rgb(255, 92, 43);"
        )
        self.label_10.setObjectName("label_10")
        self.txt_phongchieu = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_phongchieu.setGeometry(QtCore.QRect(590, 280, 221, 31))
        self.txt_phongchieu.setStyleSheet(
            "border: 3px solid white ; /* Đường viền đen dày 2px */\n"
            'font: 10pt "MS Shell Dlg 2";\n'
            "border-radius: 15px;"
        )
        self.txt_phongchieu.setReadOnly(True)
        self.txt_phongchieu.setObjectName("txt_phongchieu")
        self.time_begin = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_begin.setGeometry(QtCore.QRect(590, 410, 111, 31))
        self.time_begin.setObjectName("time_begin")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 140, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 410, 81, 20))
        self.label_6.setStyleSheet('font: 10pt "MS Shell Dlg 2";')
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(430, 30, 20, 621))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.date_ngaychieu = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_ngaychieu.setGeometry(QtCore.QRect(590, 340, 111, 31))
        self.date_ngaychieu.setReadOnly(True)
        self.date_ngaychieu.setObjectName("date_ngaychieu")
        self.table_lichchieu = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_lichchieu.setGeometry(QtCore.QRect(40, 220, 321, 191))
        self.table_lichchieu.setObjectName("table_lichchieu")
        self.table_lichchieu.setColumnCount(5)
        self.table_lichchieu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lichchieu.setHorizontalHeaderItem(4, item)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 350, 81, 20))
        self.label_5.setStyleSheet('font: 10pt "MS Shell Dlg 2";')
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 470, 81, 20))
        self.label_7.setStyleSheet('font: 10pt "MS Shell Dlg 2";')
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(710, 70, 201, 41))
        self.label_2.setStyleSheet('font: 14pt "MS Shell Dlg 2";')
        self.label_2.setObjectName("label_2")
        self.button_xoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_xoa.setGeometry(QtCore.QRect(740, 540, 75, 41))
        self.button_xoa.setStyleSheet(
            'font: 10pt "MS Shell Dlg 2";\n'
            "border: 1px solid white ; /* Đường viền đen dày 2px */\n"
            "border-radius: 15px;\n"
            "background-color: #e74c3c;\n"
            " color: #ffffff;"
        )
        self.button_xoa.setObjectName("button_xoa")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(496, 220, 61, 20))
        self.label_3.setStyleSheet('font: 10pt "MS Shell Dlg 2";')
        self.label_3.setObjectName("label_3")
        self.button_timkiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_timkiem.setGeometry(QtCore.QRect(260, 110, 81, 41))
        self.button_timkiem.setStyleSheet(
            'font: 10pt "MS Shell Dlg 2";\n'
            "border: 3px solid white ; /* Đường viền đen dày 2px */\n"
            "border-radius: 15px;\n"
            "background-color:#27ae60;\n"
            " color: #ffffff;"
        )
        self.button_timkiem.setObjectName("button_timkiem")
        self.time_end = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_end.setGeometry(QtCore.QRect(590, 460, 111, 31))
        self.time_end.setReadOnly(True)
        self.time_end.setObjectName("time_end")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(470, 20, 211, 171))
        self.widget.setObjectName("widget")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 161, 151))
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setPixmap(QtGui.QPixmap("public/clapperboard.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.button_quayve = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_quayve.setGeometry(QtCore.QRect(40, 440, 321, 41))
        self.button_quayve.setStyleSheet(
            "\n"
            'font: 10pt "MS Shell Dlg 2";\n'
            "border: 5px solid white ; /* Đường viền đen dày 2px */\n"
            "border-radius: 15px;\n"
            "background-color:#e67e22;\n"
            " color: #ffffff;"
        )
        self.button_quayve.setObjectName("button_quayve")
        self.combox_tenphim = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combox_tenphim.setGeometry(QtCore.QRect(590, 220, 221, 31))
        self.combox_tenphim.setStyleSheet(
            "border: 3px solid white ; /* Đường viền đen dày 2px */\n"
            'font: 10pt "MS Shell Dlg 2";\n'
            "border-radius: 15px;"
        )
        self.combox_tenphim.setObjectName("combox_tenphim")

        self.retranslateUi(them_lichchieu)
        QtCore.QMetaObject.connectSlotsByName(them_lichchieu)

    def retranslateUi(self, them_lichchieu):
        _translate = QtCore.QCoreApplication.translate
        them_lichchieu.setWindowTitle(_translate("them_lichchieu", "MainWindow"))
        self.label.setText(_translate("them_lichchieu", "BỘ LỌC LỊCH CHIẾU"))
        self.button_sua.setText(_translate("them_lichchieu", "Thêm"))
        self.label_4.setText(_translate("them_lichchieu", "Phòng chiếu"))
        self.label_10.setText(
            _translate("them_lichchieu", "Vui lòng nhập đầy đủ thông tin")
        )
        self.comboBox.setItemText(0, _translate("them_lichchieu", "Phòng 1"))
        self.comboBox.setItemText(1, _translate("them_lichchieu", "Phòng 2"))
        self.comboBox.setItemText(2, _translate("them_lichchieu", "Phòng 3"))
        self.comboBox.setItemText(3, _translate("them_lichchieu", "Phòng 4"))
        self.label_6.setText(_translate("them_lichchieu", "Giờ bắt đầu"))
        item = self.table_lichchieu.horizontalHeaderItem(0)
        item.setText(_translate("them_lichchieu", "Tên phim"))
        item = self.table_lichchieu.horizontalHeaderItem(1)
        item.setText(_translate("them_lichchieu", "Phòng chiếu"))
        item = self.table_lichchieu.horizontalHeaderItem(2)
        item.setText(_translate("them_lichchieu", "Ngày chiếu"))
        item = self.table_lichchieu.horizontalHeaderItem(3)
        item.setText(_translate("them_lichchieu", "Giờ bắt đầu"))
        item = self.table_lichchieu.horizontalHeaderItem(4)
        item.setText(_translate("them_lichchieu", "Giờ kết thúc"))
        self.label_5.setText(_translate("them_lichchieu", "Ngày chiếu"))
        self.label_7.setText(_translate("them_lichchieu", "Giờ kết thúc"))
        self.label_2.setText(_translate("them_lichchieu", "THÊM LỊCH CHIẾU"))
        self.button_xoa.setText(_translate("them_lichchieu", "Xoá"))
        self.label_3.setText(_translate("them_lichchieu", "Tên phim"))
        self.button_timkiem.setText(_translate("them_lichchieu", "Tìm kiếm"))
        self.button_quayve.setText(
            _translate("them_lichchieu", "QUAY LẠI DANH SÁCH LỊCH CHIẾU")
        )
        self.setEvent()
        self.getMovie()

    def setEvent(self):
        self.button_timkiem.mousePressEvent = self.searchTimKiem

    def searchTimKiem(self, event):
        date = self.date_timkiem.text()
        selected_room = self.comboBox.currentText()
        result = self.lichChieuController.searchTimKiem(date, selected_room)
        if result.success == False:
             toast.toastWarning(result.message)
             return
        self.putdata(result.data)
        return
    #đẩy dữ liệu tìm kiếm lên table
    def putdata(self, data: list):
        self.table_lichchieu.setRowCount(len(data))
        for row_idx, row_data in enumerate(data):
            self.table_lichchieu.setItem(row_idx, 0, QtWidgets.QTableWidgetItem(str(row_data["name"])))
            self.table_lichchieu.setItem(row_idx, 1, QtWidgets.QTableWidgetItem(str(row_data["room"])))
            self.table_lichchieu.setItem(row_idx, 2, QtWidgets.QTableWidgetItem(str(row_data["day"])))
            self.table_lichchieu.setItem(row_idx, 3, QtWidgets.QTableWidgetItem(str(row_data["timestart"])))
            self.table_lichchieu.setItem(row_idx, 4, QtWidgets.QTableWidgetItem(str(row_data["timeend"])))

    def getMovie(self):
        result = self.lichChieuController.fetch_movie()
        if result.success is False:
            toast.toastWarning(result.message)
            return
        
        self.listMovie = result.data
        for movie in self.listMovie:
            self.combox_tenphim.addItem(movie["name"])
        
        # lấy index đang select cảu combobõ tên phim
        # tương ứng với index trong listmovie

        # muốn lấy id phim đang muốn thêm lịch thì sẽ lấy phần tử thứ index của listmovie






if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    them_lichchieu = QtWidgets.QMainWindow()
    ui = Ui_them_lichchieu()
    ui.setupUi(them_lichchieu)
    them_lichchieu.show()
    sys.exit(app.exec())
